### ISSUE TITLE
Jormungandr syncing issues on incentivized testnet

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/jormungandr#1146]
**Describe the bug**
When Starting Jormungandr, I don't see it fetching any blocks from the network:
```
state = Running
blockRecvCnt = 0
lastBlockDate = 0.133570
lastBlockFees = 0
lastBlockHash = 5954d915e9f66bef8fd69cfded3c7962623a76e4c1c2a611bc18e4fe75d865a9
lastBlockHeight = 4000
lastBlockSum = 0
lastBlockTime = 
lastBlockTx = 0
txRecvCnt = 0
uptime = 1921
```
 

I.e.:
Starting "cold" (dir storage `data_incentivized` does not exist):
```
jormungandr --genesis-block-hash 0f9d564199ad7f71af3daaff4b6997cb7f2e3d7c422fa29097f5d6a018c440d1 --rest-listen 127.0.0.1:8080 --storage ./data_incentivized/chain --config node_config_incentivized.yaml
```
node_config_incentivized.yaml: 
```
--- 
log: 
  format: plain
  level: info
  output: stderr
p2p: 
  listen_address: /ip4/0.0.0.0/tcp/3001
  topics_of_interest: 
    blocks: high
    messages: high
  trusted_peers:  
    [
      {
        "address": "/ip4/54.183.206.246/tcp/3000",
        "id": "67282e0bf1dcdf5e4559c85b057de122ba7a248f16ac5226"
      },
      {
        "address": "/ip4/52.8.126.235/tcp/3000",
        "id": "75534bbbb7dddfeee3783ae5e7983c28349209138351c278"
      },
      {
        "address": "/ip4/3.113.195.95/tcp/3000",
        "id": "617ff3920bac9e90faec3adc5d32c2937cbb6b8528b1b22d"
      },
      {
        "address": "/ip4/18.176.14.159/tcp/3000",
        "id": "55f82104122f4d5101ae549935943071c8c646f1bd62cd0b"
      },
      {
        "address": "/ip4/3.124.166.70/tcp/3000",
        "id": "96a84a81a74715c7fb29d906ddff32b2874aac4d14acc7db"
      },
      {
        "address": "/ip4/3.125.15.153/tcp/3000",
        "id": "97fd215d7e294b5943960056af1e1a0316c3593a4aa3cb76"
      },
      {
        "address": "/ip4/3.124.103.156/tcp/3000",
        "id": "173ca3b1198816989c585785a8c912fea3c5ec14895eaa6b"
      }
]
```

**Mandatory Information**
`jormungandr 0.7.0 (HEAD-a93d4f6, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
`

**To Reproduce**
1. Start jormungandr with no storage on disk (from previous start)

**Expected behavior**
Jormungandr connects to network and starts receiving blocks.

**Additional context**
`blockRecvCnt = 0`
The same config, and start cmd worked fine for me on 15th Nov.

**Comment by NicolasDP** [comment]
I can't reproduce the issue. Are you sure it is still there?

**Comment by piotr-iohk** [comment]
> I can't reproduce the issue. Are you sure it is still there?

Indeed, I don't see it any longer now. I.e. The node started receiving blocks for me.

I can observe however that blocks are received in "bulks" and after each bulk of blocks received my jormungandr gets "stucked" for a moment.

E.g.

I get to `blockRecvCnt = 4000` and get stuck for a while.
I get to `blockRecvCnt = 8000` and get stuck for a while.
I get to `blockRecvCnt = 18000` and get stuck for a while.
etc.

Not sure if this is something that is expected, but I think that it might be the reason of the observations on Daedalus side why during initial syncing sync progress gets stuck at 1%,3%,6%... etc. after getting fully synced:
https://input-output-rnd.slack.com/archives/C7PJ29FME/p1574050116373300

I think that it might be also a problem after one gets fully synced and observes that Daedalus periodicallly gets out-of sync: https://input-output-rnd.slack.com/archives/GJY4XC3DM/p1573819493114400?thread_ts=1573792617.099900&cid=GJY4XC3DM

Currently, after the trusted nodes have been restarted, it looks healthy and those "hangs" are not very long, but I think, when the network is more "busy"/nodes are overloaded (like this morning) it seems to be a problem.

**Comment by NicolasDP** [comment]
Thanks. It makes perfect sense under the current settings that wallet's won't sync very often. But instead will be notified of new block when appropriate.

In order to deliver a good support for unreachable nodes in the required time, we provided a new kind of node: unreadable. They are the default one. The one that cannot be publicly reachable. They are nomads, behind a firewall in an airport or using a public wifi. Or they are the default users at home (for now at least), that cannot/won't change the NAT settings to be a publicly reachable node.

In order to mitigate them, the non publicly reachable nodes, they have been put in a special place in the p2p topology. They are not gossiped about (yet they receive gossips and connect to other nodes). They are queued and process in a completely random way. This is the most fair and appropriate way to deal with these kind of nodes in the context of decentralisation. However, with the settings for the balance check. There is no incentive (except for IOHK) to provide new publicly reachable nodes in the network. Right now, only IOHK's nodes are contacted to provide updates on the blockchain. This is still pretty much the current settings of haskell mainnet. In order to mitigate the load, new nodes need to be spawned.

There is something we can do, in the meanwhile, to provide more control to devops. That will be useful in the long run for other stake pools:

- allow nodes to change the value of non publicly reachable nodes to be notified at a time (#1150)
- enhance the network end points to give more info on the topology (#1149)

**Comment by carl-IOHK** [comment]
Linked to https://iohk.myjetbrains.com/youtrack/issue/IOHKS-154

**Comment by ziro-official** [comment]
Is there any faucet for incentivized testnet?

**Comment by NicolasDP** [comment]
@ziro-official : https://iohk.zendesk.com/hc/en-us/categories/360002392053-Shelley-Incentivized-Testnet
