### ISSUE TITLE
Stake pool ID divergence between the pool registry design document and the implementation

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/jormungandr#1200]
The "Stakepool Registration for Jormungandr Incentivized Testnet" document (https://input-output.atlassian.net/wiki/spaces/CIR/pages/841253142/Stakepool+Registration+for+Jormungandr+Incentivized+Testnet) specified the stake pool IDs to be:

> The repository would act as a public registry listing .json files identified by the stake pool on-chain ids (a.k.a public keys)

The particular kind of public key was chosen at the registry implementation time based on Slack discussions with developers -- `ed25519` was suggested.

Recently it was observed that the codebase actually has a different notion of the stake pool ID, and one suggestion is that it is:

`pub type PoolId = DigestOf<Blake2b256, PoolRegistration>;`

This breaks the stake pool registry entry submission validator (https://github.com/input-output-hk/testnet-stake-pool-registry-validator) -- both its functionality and the test suite it has.

**Comment by vincenthz** [comment]
This is a problem with inventing a "design document" that had no bearing with reality. The internal (sic) document has been created end of September, whereas the real design happened in February and the solution has implemented between March and April (without any change since).

Sadly, the only solution is fix the "design document".
