### ISSUE TITLE
0.8.0-rc1: shutdowns, stability issues

### ISSUE THREAD

**Issue by manveru** [input-output-hk/jormungandr#1232]
**Describe the bug**

Node crashes, startup issues and failure to create blocks on nightly testnet.
There is no log of crashes or errors, but the nodes spontaneously shut down. The ones that stay up have been neither applying nor producing blocks. Regular restarts of nodes stuck in Bootstrapping state seems to unblock others for a little bit, but soon gets dysfunctional again.

**Mandatory Information**
1. `jcli 0.8.0-rc1 (, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`
2. `jormungandr 0.8.0-rc1 (, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by feqifei** [comment]
I faced the same situation during the whole day, stuck during the bootstrap, but during last hour attempts it stuck just on the init task. Not able to download even the genesis block, 
In the storage folder only the blocks.sqlite file remains, the other ones are deleted.
Nov 29 14:55:50.465 WARN failed to download block, error: GetBlocksStream { source: Error { code: NotFound, source: Status { code: NotFound, message: "not found" } } }, peer_address: 184.169.162.15:3000, block: dceef4d6696ead83eadb5104c6383e1905aa81fc7a79ea2ca87a97c2bfd2f4a1, task: init
Error fetching the genesis block from the network
 |-> could not download block hash dceef4d6696ead83eadb5104c6383e1905aa81fc7a79ea2ca87a97c2bfd2f4a1

**Comment by manveru** [comment]
Quick update, we reset the entire nightly network with a new genesis (including incentives) and it seems pretty healthy so far.
We'll see how it fares once more people connect.

**Comment by hodlonaut** [comment]
Experienced unexpected shutdown shortly after node startup on private testnet using 0.8 rc1 this morning: 

Nov 30 08:30:29.078 INFO block successfully applied, date: 67.254, parent: a3d01c088a9e241caa7a73046d5cd9c851f9e85334cf749165bddf782dede20f, hash: d86ee9ad7e788a8fe600a5e67e845a2b863ae126d2f2a113e6e118c261237f0a, task: block
Nov 30 08:30:29.078 INFO update current branch tip, task: block
Nov 30 08:30:29.421 ERRO cannot compute the time passed since the last block: second time provided was later than self, task: stuck_notifier
Nov 30 08:30:29.421 INFO service finished with error, task: stuck_notifier
Nov 30 08:30:29.421 INFO Shutting down node
