### ISSUE TITLE
0.8 rc2 - rewards not being paid out as expected (private testnet)

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/jormungandr#1237]
jormungandr --full-version
jormungandr 0.8.0-rc1 (master-ea02e870+, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

Genesis settings pertaining to awards:
 treasury: 10
  treasury_parameters:
    fixed: 100
    ratio: 1/25
    max_limit: 1000
  total_reward_supply: 200000000000
  reward_parameters:
    linear:
      constant: 10000
      ratio: 1000/1
      epoch_start: 1
      epoch_rate: 5

pool settings:

jcli rest v0 stake-pool  get b819e390d62aa75efd0c00b704b9e22fbbcbbfcc93d24dd128f038510acf7241
---
kesPublicKey: kes25519-12-pk16e7dqwq6ugw447xa3j5r22hdk22gptsyy4ety4avhwz6uees84nqv7wand
tax:
  fixed: 0
  max: 10000000
  ratio:
    denominator: 10
    numerator: 1
total_stake: 1500000260

Node is generating dozens of blocks per epoch, no sign of any lovelaces being added to either account associated with pool creation, or separate account that just delegated 1/3 of the delegation total to the pool.

No clues as debug logging doesn't show anything of interest near epoch boundary

**Comment by hodlonaut** [comment]
Looks like primary cause is this check returning 0 in distribute_rewards, while seemingly having a look at leaders_log entries associated with an epoch <new epoch - 2> from what I can tell (around the time of the transition from new epoch - 1 to new epoch):

        if self.leaders_log.total() == 0 {
            return Ok(new_ledger);
        }

**Comment by NicolasDP** [comment]
excellent. Thanks. Based on the data you gave me I narrowed down the issue. We thought it was a problem down in the ledger. Actually the issue is there https://github.com/input-output-hk/jormungandr/blob/ea02e8701382a596ca67131c2204e49fcdc05103/jormungandr/src/blockchain/chain.rs#L763-L777

The epoch state is used to compute how the leadership was going to be setup up. But the reward was has been ignored and set to the wrong object. Thanks to your help I'll be able to fix this ASAP and will cut a release for that.
