### ISSUE TITLE
logging improvement epoch.block time

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/jormungandr#1251]
**Is your feature request related to a problem/context ? Please describe if applicable.**
After Date time also show epoch.block in logfiles

For example for epoch 23 and blockDate 286 show

`Dec 02 20:30:17.123  23.286 INFO ...`

I admit this can be confusing when the logged message is related to a different (older/newer) block, but it can help to understand in what situation the node received and processed data related to this log message.

**Comment by mzabaluev** [comment]
It's not always possible to log a specific branch tip as the current block date, and due to how things are separated in the internal architecture, some tasks do not have this information. In some contexts, such as processing blocks from the network, logging the main branch tip is misleading as other nodes may propagate competing branches.

I suggest breaking down this request, to add information in specific contexts where it might be helpful. For detecting the situation when no progress is made, we already have the `stuck_notifier`.
