### ISSUE TITLE
The lastBlockTime increases but lastBlockHeight freezes

### ISSUE THREAD

**Issue by prographo** [input-output-hk/jormungandr#1402]
```
ubuntu@ip-172-31-14-999:~$ . cn
blockRecvCnt: 16
lastBlockContentSize: 0
lastBlockDate: "5.28352"
lastBlockFees: 0
lastBlockHash: 59eed5dd5b043cc0563bf29b5e100e02d29d82ee78dec6d6aa961230f581ac79
lastBlockHeight: "20040"
lastBlockSum: 0
lastBlockTime: "2019-12-19T10:58:42+00:00"
lastBlockTx: 0
state: Running
txRecvCnt: 3
uptime: 811
version: jormungandr 0.8.3-8f276c0

ubuntu@ip-172-31-14-999:~$ . cn
blockRecvCnt: 19
lastBlockContentSize: 0
lastBlockDate: "5.28352"
lastBlockFees: 0
lastBlockHash: 59eed5dd5b043cc0563bf29b5e100e02d29d82ee78dec6d6aa961230f581ac79
lastBlockHeight: "20040"
lastBlockSum: 0
lastBlockTime: "2019-12-19T11:03:22+00:00"
lastBlockTx: 0
state: Running
txRecvCnt: 5
uptime: 943
version: jormungandr 0.8.3-8f276c0

ubuntu@ip-172-31-14-999:~$ cat cn
./jcli rest v0 node stats get --host "http://127.0.0.1:3100/api"
ubuntu@ip-172-31-14-999:~$ ./jormungandr -V
jormungandr 0.8.3
```

**Comment by A-Caccese** [comment]
I had the same issue. I'm not sure, but I think that this behaviour can be mitigated using a different port for listen address and public address.

**Comment by rinor** [comment]
Thank you for reporting it. This is somewhat similar or the same as https://github.com/input-output-hk/jormungandr/issues/1303. Now the situation is a bit more complex due to the forks going round. There is also the issue that the lastBlockTime reported there is somewhat wrong since it does not refer exactly to the mentioned hash correlated to the “main” chain, but to a fork... there is more to this and I will upload more details shortly.

**Comment by rinor** [comment]
@prographo can you confirm that you do not have this issue on v0.8.5, meaning that if `lastBlockHeight` does not change the same happens to `lastBlockTime` (not taking in consideration the reason(s) why the node may become stuck, since is tracked in different other issues). Thank you.

**Comment by prographo** [comment]
I retest on 0.8.5 - seems fixed.

**Comment by rinor** [comment]
@prographo thank you for the feedback.
