### ISSUE TITLE
Blockchain is not moving up - jormungandr v0.8.5

### ISSUE THREAD

**Issue by napangelo** [input-output-hk/jormungandr#1479]
Hi,
I use jormungandr v0.8.5, every time I start it after a few hours it leaves the frequent warning "Blockchain is not moving upwards, the last block was [n] seconds".
Why?

**Comment by stakehodlers** [comment]
Seems to be a duplicate of issue 1470... thanks for reporting!

**Comment by rinor** [comment]
@napangelo `blockchain is not moving up` is a symptom and not the issue per se. While a notification that your node may be stuck and/or not synching anymore, it can be caused by different issues already reported and being tracked. Thanking you for the report, do you think you can close this one since a bit too generalistic. Thank you.
