### ISSUE TITLE
REST API - leaders registration - Registering twice the same leader is allowed

### ISSUE THREAD

**Issue by wxsq2004** [input-output-hk/jormungandr#1498]
**Describe the bug**
Registering twice the same leader with the same parameters through REST endpoing POST /api/v0/leaders is allowed and returns 2 different leader ids.

**Mandatory Information**
1. jcli 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Register a leader with REST endpoing POST /api/v0/leaders
2. Register again the same leader. Call does not fail, and a new id is returned

**Expected behavior**
The second call should fail

**Comment by juknekky** [comment]
Brave, Merchants MeridianSMORES YUMMM

**Comment by matthijs-last** [comment]
Witnessed the same behavior running 0.8.8.

jcli 0.8.8 (HEAD-4687999, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
jormungandr 0.8.8 (HEAD-4687999, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

Managed to create an adversarial fork block with leaders posted twice on same node:

- created_at_time: "2020-02-03T19:13:50.570084482+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-02-03T20:52:45.459083178+00:00"
  scheduled_at_date: "52.2974"
  scheduled_at_time: "2020-02-03T20:52:45+00:00"
  status:
    Block:
      block: 9898fd0595df080c13315a327c840a12fa0afb0fa22b9ee15d5cf633de3640a7
      chain_length: 161039
  wake_at_time: "2020-02-03T20:52:45.450882846+00:00"

- created_at_time: "2020-02-03T19:14:03.404521497+00:00"
  enclave_leader_id: 2
  finished_at_time: "2020-02-03T20:52:45.030464947+00:00"
  scheduled_at_date: "52.2974"
  scheduled_at_time: "2020-02-03T20:52:45+00:00"
  status:
    Block:
      block: a4922f2c50f950d3e0a3b1ca48545df932b9501bd9828cae74f9a40bac8b87f4
      chain_length: 161039
  wake_at_time: "2020-02-03T20:52:45.030250824+00:00"


And received 'Not computing this schedule because of invalid state against the network blockchain':

- created_at_time: "2020-02-03T19:14:03.404561041+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-02-04T08:11:53.102221780+00:00"
  scheduled_at_date: "52.23348"
  scheduled_at_time: "2020-02-04T08:11:53+00:00"
  status:
    Block:
      block: c389bdd3660112b0692e7253845311cac208404eafff388d2d16ea91f88c8a65
      chain_length: 162509
  wake_at_time: "2020-02-04T08:11:53.096940044+00:00"

- created_at_time: "2020-02-03T19:14:03.404561891+00:00"
  enclave_leader_id: 2
  finished_at_time: "2020-02-04T08:11:53.107542375+00:00"
  scheduled_at_date: "52.23348"
  scheduled_at_time: "2020-02-04T08:11:53+00:00"
  status:
    Rejected:
      reason: Not computing this schedule because of invalid state against the network blockchain
  wake_at_time: "2020-02-04T08:11:53.107513562+00:00"

**Comment by matthijs-last** [comment]
Witnessed the same behavior running 0.8.8.

jcli 0.8.8 (HEAD-4687999, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
jormungandr 0.8.8 (HEAD-4687999, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

Managed to create an adversarial fork block with leaders posted twice on same node:

    created_at_time: "2020-02-03T19:13:50.570084482+00:00"
    enclave_leader_id: 1
    finished_at_time: "2020-02-03T20:52:45.459083178+00:00"
    scheduled_at_date: "52.2974"
    scheduled_at_time: "2020-02-03T20:52:45+00:00"
    status:
    Block:
    block: 9898fd0595df080c13315a327c840a12fa0afb0fa22b9ee15d5cf633de3640a7
    chain_length: 161039
    wake_at_time: "2020-02-03T20:52:45.450882846+00:00"

    created_at_time: "2020-02-03T19:14:03.404521497+00:00"
    enclave_leader_id: 2
    finished_at_time: "2020-02-03T20:52:45.030464947+00:00"
    scheduled_at_date: "52.2974"
    scheduled_at_time: "2020-02-03T20:52:45+00:00"
    status:
    Block:
    block: a4922f2c50f950d3e0a3b1ca48545df932b9501bd9828cae74f9a40bac8b87f4
    chain_length: 161039
    wake_at_time: "2020-02-03T20:52:45.030250824+00:00"

And received 'Not computing this schedule because of invalid state against the network blockchain':

    created_at_time: "2020-02-03T19:14:03.404561041+00:00"
    enclave_leader_id: 1
    finished_at_time: "2020-02-04T08:11:53.102221780+00:00"
    scheduled_at_date: "52.23348"
    scheduled_at_time: "2020-02-04T08:11:53+00:00"
    status:
    Block:
    block: c389bdd3660112b0692e7253845311cac208404eafff388d2d16ea91f88c8a65
    chain_length: 162509
    wake_at_time: "2020-02-04T08:11:53.096940044+00:00"

    created_at_time: "2020-02-03T19:14:03.404561891+00:00"
    enclave_leader_id: 2
    finished_at_time: "2020-02-04T08:11:53.107542375+00:00"
    scheduled_at_date: "52.23348"
    scheduled_at_time: "2020-02-04T08:11:53+00:00"
    status:
    Rejected:
    reason: Not computing this schedule because of invalid state against the network blockchain
    wake_at_time: "2020-02-04T08:11:53.107513562+00:00"

**Comment by matthijs-last** [comment]
Witnessed the same behavior running 0.8.8.

jcli 0.8.8 (HEAD-4687999, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
jormungandr 0.8.8 (HEAD-4687999, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

Managed to create an adversarial fork block with leader posted twice on same node:

    created_at_time: "2020-02-03T19:13:50.570084482+00:00"
    enclave_leader_id: 1
    finished_at_time: "2020-02-03T20:52:45.459083178+00:00"
    scheduled_at_date: "52.2974"
    scheduled_at_time: "2020-02-03T20:52:45+00:00"
    status:
    Block:
    block: 9898fd0595df080c13315a327c840a12fa0afb0fa22b9ee15d5cf633de3640a7
    chain_length: 161039
    wake_at_time: "2020-02-03T20:52:45.450882846+00:00"

    created_at_time: "2020-02-03T19:14:03.404521497+00:00"
    enclave_leader_id: 2
    finished_at_time: "2020-02-03T20:52:45.030464947+00:00"
    scheduled_at_date: "52.2974"
    scheduled_at_time: "2020-02-03T20:52:45+00:00"
    status:
    Block:
    block: a4922f2c50f950d3e0a3b1ca48545df932b9501bd9828cae74f9a40bac8b87f4
    chain_length: 161039
    wake_at_time: "2020-02-03T20:52:45.030250824+00:00"

And received 'Not computing this schedule because of invalid state against the network blockchain':

    created_at_time: "2020-02-03T19:14:03.404561041+00:00"
    enclave_leader_id: 1
    finished_at_time: "2020-02-04T08:11:53.102221780+00:00"
    scheduled_at_date: "52.23348"
    scheduled_at_time: "2020-02-04T08:11:53+00:00"
    status:
    Block:
    block: c389bdd3660112b0692e7253845311cac208404eafff388d2d16ea91f88c8a65
    chain_length: 162509
    wake_at_time: "2020-02-04T08:11:53.096940044+00:00"

    created_at_time: "2020-02-03T19:14:03.404561891+00:00"
    enclave_leader_id: 2
    finished_at_time: "2020-02-04T08:11:53.107542375+00:00"
    scheduled_at_date: "52.23348"
    scheduled_at_time: "2020-02-04T08:11:53+00:00"
    status:
    Rejected:
    reason: Not computing this schedule because of invalid state against the network blockchain
    wake_at_time: "2020-02-04T08:11:53.107513562+00:00"
