### ISSUE TITLE
49 epochs, 23 slots, 0 successful blocks

### ISSUE THREAD

**Issue by dogpatchmedia** [input-output-hk/jormungandr#1693]
**Describe the bug**
every time i get a slot it doesn't count. this is not right nor is it fair. 

Feb  1 05:24:11 ns102521 jormungandr[56052]: Feb 01 05:24:11.001 INFO receiving block from leadership service, date: 49.18317, parent: 82539918f9dd735f13d6618779ebfe02dd6047bf87380802eae5a2043f13c1cb, hash: 58e1665570e3e5c7016d0e3e27c88d9e7aed5d2a6ab182d7ae7b1d7b1b1bdb9c, task: block
Feb  1 05:24:11 ns102521 jormungandr[56052]: Feb 01 05:24:11.002 DEBG processing block from leader event, date: 49.18317, parent: 82539918f9dd735f13d6618779ebfe02dd6047bf87380802eae5a2043f13c1cb, hash: 58e1665570e3e5c7016d0e3e27c88d9e7aed5d2a6ab182d7ae7b1d7b1b1bdb9c, task: block
Feb  1 05:24:11 ns102521 jormungandr[56052]: Feb 01 05:24:11.002 ERRO cannot process leadership block, reason: Error(Inner(Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Block proof is invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } }))), date: 49.18317, parent: 82539918f9dd735f13d6618779ebfe02dd6047bf87380802eae5a2043f13c1cb, hash: 58e1665570e3e5c7016d0e3e27c88d9e7aed5d2a6ab182d7ae7b1d7b1b1bdb9c, task: block

**Comment by SudoStake** [comment]
Have you looked at this guide on how to configure your node? https://github.com/Chris-Graffagnino/Jormungandr-for-Newbs/blob/master/docs/jormungandr_node_setup_guide.md

This is also a useful guide that may help compare with the first guide. https://gist.github.com/ilap/54027fe9af0513c2701dc556221198b2

I would also recommend running `jcli rest v0 leaders logs get` routinely and you can see when your node is elected next to mint a block and if it was successful. 

My current node only needs 2 vcpu and 4 GB of memory.

**Comment by vincenthz** [comment]
while I sympathised with the issue, apart from the network woes and improvement to chains that we're looking into, the problem described above, with unnecessary strong language, is the protocol behaviour that will not change in any meaningful way.

The key issue that people will have to accept is, it's not because that you are given permission to create a block, that you are the only one that has this permission. Every stake pools on the network will *independently* evaluate whether they have a given slot. Figuratively speaking it means that every stake pools has a set of dice with their own specific value that they need to reach (their stake), and they all roll their own dice at the same time for a chance to speak. Every stake pool that passed the first test, then try to broadcast their work (the block) all at the same time, and the one most likely to succeed is the one with the best broadcasting ability (network, connectivity to other pools, luck).

Sadly with only 23 slots elected over 49 epochs, the chance that any of those 23 slots are unique on this global private election run is extremely slim.

As to the block verification proof issue, which we haven't explained yet, we're looking into it at #1128 and https://github.com/input-output-hk/chain-libs/pull/249
