### ISSUE TITLE
`jcli rest v0 stake-pool get` and `jcli rest v0 stake get` are returning different stake delegation per pool

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1747]
**Describe the bug**
`jcli rest v0 stake-pool get` and `jcli rest v0 stake get` are returning different stake delegation per pool

**Mandatory Information**
```
jcli 0.8.9 (HEAD-30d20d2e, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
jormungandr 0.8.9 (HEAD-30d20d2e, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
```

**To Reproduce**
1. Start a local node and wait for it to be synced to the latest block height
2. execute both below commands one after that other 
```
jcli rest v0 stake-pool get fdbedc0c257a7ac5ae93a1808277325cca9c39d3c262a0e09d510ac9ff3d0fb4 -h http://127.0.0.1:9000/api
jcli rest v0 stake get --host "http://127.0.0.1:9000/api"
```
3. compare the `total_stake` value for the pool returned by both commands.

**Expected behavior**
Both commands should return the same values for the `stake delegation` per pool.

**Additional context**
```
jcli rest v0 node stats get --host "http://127.0.0.1:9000/api"
---
blockRecvCnt: 204
lastBlockContentSize: 0
lastBlockDate: "55.24926"
lastBlockFees: 0
lastBlockHash: 0847a490979b68d7eed6837e94fd278817d1a6d639e3d51439c0607627044bec
lastBlockHeight: "172604"
lastBlockSum: 0
lastBlockTime: "2020-02-07T09:04:29+00:00"
lastBlockTx: 0
lastReceivedBlockTime: "2020-02-07T09:04:31+00:00"
peerAvailableCnt: 4228
peerQuarantinedCnt: 9132
peerUnreachableCnt: 0
state: Running
txRecvCnt: 25
uptime: 3677
version: jormungandr 0.8.9-30d20d2e
```

**Comment by Straightpool** [comment]
This is not a bug, but a feature. "Stake get" returns the live stake and "Stake-pool get" the effective stake.

**Comment by dorin100** [comment]
and what is the difference between the 2 @Straightpool ? + is there is a difference, where do you find about it? thank you!

**Comment by Straightpool** [comment]
Live stake is the current delegated stake minute by minute. So lets say someone delegated 10M ADA to your pool right now, your live stake increases by 10M ADA. It takes at least one epoch transition for live stake to become active and play any role in the stake lottery. If this delegator e.g. pulls the 10M ADA from your pool before the epoch transition happens your live stake will be updated immediately but your effective stake will never change as the delegation never got effective.

The difference has been discussed in the Stake Pool Best Practice Telegram. 

I agree the wording of the API calls could be improve like Stake-live get and Stake-effective get instead of Stake get and Stake-pool get.

**Comment by dorin100** [comment]
Thank you @Straightpool , @rinor ; It makes sense now.
