### ISSUE TITLE
v0.8.9 I get the error report of node stuck, but the node running well

### ISSUE THREAD

**Issue by crackerli** [input-output-hk/jormungandr#1824]
I'm running a stake pool on aws server, today when I check the history log, I found the error output like below:
ERRO cannot compute the time passed since the last block: second time provided was later than self, task: stuck_notifier

Then I check the node stats, it is syncing with the network, I want to know what happened and what I should do to avoid those stuck?

**Comment by dmindfuse** [comment]
It’s your shout of course, but in the interest of advancing the testnet and helping with providing IOHK relevant and up to date blockchain data, is there a reason why you are not yet on v0.8.13? Lots of fixes and optimizations went into newer versions. Experience gathered is possibly flowing into the Haskell edition. I’d look into upgrading versus opening tickets for outdated versions, despite claims of 0.8.9 being more stable. This is a testnet and we should be testing new versions and sorting out open issues fast rather than honding on to an old version. At least that is my personal opinion. There’ll be plenty of staking on mainnet later. Please consider. :)

**Comment by eugene-babichenko** [comment]
> `ERRO cannot compute the time passed since the last block: second time provided was later than self, task: stuck_notifier`

This error does not mean that the node is stuck, but that there was something wrong with checking if it was stuck. Do you see this message all the time, or there are a couple of occasional messages?

**Comment by crackerli** [comment]
> > `ERRO cannot compute the time passed since the last block: second time provided was later than self, task: stuck_notifier`
> 
> This error does not mean that the node is stuck, but that there was something wrong with checking if it was stuck. Do you see this message all the time, or there are a couple of occasional messages?

Thank you for your reply, there are a couple of occasional messages. If the jormungandr halted, I can see this message all the time, then I need to restart it.
Anyway, as the day of 0.8.13 released, I have migrate to 0.8.13, as 11days passed, I haven't seen this message anymore, please ignore this issue, thank you
