### ISSUE TITLE
A Single Node Generated an Adversarial Fork

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/jormungandr#1890]
**Describe the bug**
A single node, DIGI, generated an adversarial fork.

**Mandatory Information**
1. jcli 0.8.12 (HEAD-22890b72, release, macos [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]

2. jormungandr 0.8.12 (HEAD-22890b72, release, macos [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]
<img width="548" alt="Screen Shot 2020-03-08 at 11 12 22 AM" src="https://user-images.githubusercontent.com/25856278/76169227-4e1d7080-6133-11ea-95d5-237d5941a499.png">

**To Reproduce**
1. Unknown

**Expected behavior**
Single block production

**Additional context**
I am running 6 nodes in the same environment. 2 leaders and 4 passives on Mac OSX Catalina. The leader logs will not help since the block time has already been purged but I will post them here anyway. The adversarial fork, or multiple blocks did occur around the time of "spring-forward" near 3 am EST but I don't believe this is a factor since Jörmungandr is using UTC time. 
Using the Michael Fazio version 0.8.9-stable-alpha6.

The nodes have been up for 3 days and I am not using any leader swap scripts. Only one leader of each DIGI and DIGI2 are running with their own unique node_secret.yaml. See image below.

[leader_logs_too_late.log](https://github.com/input-output-hk/jormungandr/files/4303712/leader_logs_too_late.log)
<img width="1665" alt="Screen Shot 2020-03-08 at 10 54 16 AM" src="https://user-images.githubusercontent.com/25856278/76169183-f2eb7e00-6132-11ea-8407-8770ccf3a6a6.png">

**Comment by rdlrt** [comment]
The issue is unfortunately invalid for jormungandr repo.
For your reported adversarial fork on pooltool, the comparison is between two blocks at different slots - not the same.
Additionally, both of the reported blocks ( [18643](https://shelleyexplorer.cardano.org/en/block/7cdf25470be17fc406aca6b80890ea1dc6acf05e0dfd3364b63c5e9fa3e44680/) and [18634](https://shelleyexplorer.cardano.org/en/block/d9b7164c42de54c0d06a87a4268894983532507bdca958220f9b6dd8fea5abc7/) are correctly created on chain.

**Comment by rickymac68** [comment]
Closed. Thanks Priyank @rdlrt
