### ISSUE TITLE
When starting gossiping, network does not check for already connected node

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#1946]
Indeed, we call `topology.view(Any)` and quickly we already to `connect_and_propagate` with the node without checking if the node is already connected to us or not:

https://github.com/input-output-hk/jormungandr/blob/19f8eb49e15165e4a50a248e6a19221376f07cf6/jormungandr/src/network/mod.rs#L404-L414

---

instead of doing the pre-filtering of the already connected node it might be easier to do the already connected check in the `connect_and_propagate` function.

**Comment by mzabaluev** [comment]
This is happening concurrently to the server listening for new connections. If server-side subscription streams manage to be established from the same peers, propagation should use them instead of trying to connect. However, there always be the possibility of a "flare" when the inbound connection did not have time to be established (or may be stalled, which is why we should not rely on this to succeed eventually), so the client connection should proceed and replace the server connection.
