### ISSUE TITLE
Error while iterating between block0 and HEAD - deserialization error - Structure invalid: transaction when using 0.10.0-alpha.1 - b5571095

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/jormungandr#2631]
**Describe the bug**
`master` branch version of Jormungandr fails to load stored blockchain state with following error:
```
Oct 23 13:09:15.683 INFO loading from storage, currently at 84c73ea7-000af2bd-194.21981 processing=383.134122ms (153.253µs per block) ..., task: bootstrap
Error while loading the legacy blockchain state
 |-> Error while iterating between block0 and HEAD
 |-> Error while iterating between block0 and HEAD
 |-> deserialization error
 |-> Structure invalid: transaction
```

**Mandatory Information**
```
[mark_stopka@docker-host-01 srv]$ docker exec -ti 6592dfbab24e jormungandr --full-version
jormungandr 0.10.0-alpha.1 (master-b5571095, release, linux [x86_64]) - [rustc 1.47.0 (18bf6b4f0 2020-10-07)]
[mark_stopka@docker-host-01 srv]$ docker exec -ti 6592dfbab24e jcli --full-version
jcli 0.10.0-alpha.1 (master-b5571095, release, linux [x86_64]) - [rustc 1.47.0 (18bf6b4f0 2020-10-07)]
```

**To Reproduce**

**Expected behavior**
Jormungandr will be able to recover post epoch 194.

**Additional context**
N/A

**Comment by mzabaluev** [comment]
Unless the storage files were created by this exact revision of jormungandr, this is to be expected: we have changed the storage format and may make more breaking changes to it before 0.10.0 is released.

Use jormungandr 0.9.x to run an existing blockchain created by jormungandr 0.9 or earlier.
Also, it's not currently possible to bootstrap storage for a jormungandr 0.10 pre-release build in a network where jormungandr 0.9 nodes are present, due to changes in the network protocol handshake. We may decide to enable this, though.

**Comment by mark-stopka** [comment]
I see, thanks for the info, the storage was created by a different release from `master`. Nothing more to add I guess, so closing, once again, thanks!

**Comment by mark-stopka** [comment]
@pavlix FYI

**Comment by mark-stopka** [comment]
Linking for audit purposes...

https://github.com/2nd-Layer/dCloud/issues/31

**Comment by NicolasDP** [comment]
looks like it is a transaction format that is no longer compatible with the 0.9.x and earlier. Do we know what the change actually is?
