### ISSUE TITLE
Add command in jcli to convert an extended key into its key

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#451]
we need to be able to extract the ed25519 extended key from an `xprv` or an `xpub`.

```
$ jcli key generate --type=ed25519bip32 | jcli key from-extended
ed25519e_sk....
$ jcli key generate --type=ed25519bip32 | jcli key to-public | jcli key from-extended
ed25519_pk...
```

**Comment by robcohen** [comment]
Would `from-extended' be better as `to-extended`? 

It is ed25519bip32 pk/sk -> ed25519e pk/sk right? I think I am a little confused on the difference in the example for the type.

**Comment by NicolasDP** [comment]
bip32 already contains the extended part and the chain code. Here it is mainly about extracting the ed25519 key part.

**Comment by ilap** [comment]
That makes sense, but why did you introduce `Ed25519` in jormungandr?
As it will introduce complexity in Wallets. As `Ed25519` and `Ed25519Bip32` are not really compatible. 
I meant if the proper specification of the `BIP32-Ed25519` is followed (which is not case in Yoroi/Slip23/Icarus only in Daedalus;  as they clearing the bit instead of discarding a non-compatible key), then every `Ed25519Bip32`'s root and derived keys are `Ed25519` compatible, but the opposite is not true, due to the introduced 3rd highest bit clearing (In Daedalus it did some loop until it's found a compatible key).

So, you should either standardise the key derivation, signatures `BIP32-Ed25519` based on the spec, and then all key will be `Ed25519` compatible and therefore the `Ed25519` could be forgotten for signatures and use only the Bip32 one which will be the same.

As similar is done /w Bitcoin in SLIP-0010 as it's rehasing the key if it's invalid also in BIP-32, by skipping that index, despite it only has probability lower than 1 in 2^127 while in BIP32-ED25519 50%.

In the nodes it's ok, as the generated signatures either from `Ed25519` or from `Ed25519Bip32/Ext` are verifiable by the corresponding public keys, but the both generates different public keys if it's does not follow the `BIP32-ED25519` specs..

**Comment by vincenthz** [comment]
This doesn't make any sense @ilap. ed25519 is the only thing we care about at the node level; public key of the 3 schemes mentioned here, are indistinguishable from one another, regardless of bit cleared (or not) in the *secret* key.

This is making clear that the wallets can do whichever scheme that is deemed reasonable provided it comply with the ed25519 public key signature verification interface.

**Comment by ilap** [comment]
> ed25519 is the only thing we care about at the node level; public key of the 3 schemes mentioned here, are indistinguishable from one another, regardless of bit cleared (or not) in the _secret_ key.

I think I was not clear enough, I referred `jormungandr` as the whole (jormungandr and jcli) 
As I wrote above this is ok at the node level (jormungandr), as any of the signatures are verifiable with the corresponding public/verify key (they're indistinguishable at that level), and that's not the issue I was referring to.

The issue is I was referring to is relating to the client or wallet side tools (`jcli`), that why you introduced the pure `Ed25519` in `jcli` ( as not  every `Ed25519Bip32` key pairs are `Ed25519` compatible).

For example, in Yoroi, the master seed (from entropy or recovery passphares) are used for generating the `master key`, but not all of these master keys would be `Ed25519` compatible secret keys and therefore they would generate different public keys (based on the `Ed25519` spec) for abt 50% of the secret keys.

It means that 50% of the keypairs keys won't be valid `Ed25519` key pair. 

Therefore, we will have a lot of different implementations of the wallets, for choosing some ad-hoc (not standardised) master key generation (some will clear the bit, others would cherry-pickin by re HMAC ing or similar etc).

That's why some higher level (at `jcli` or wallet) standard specification should be created (similar to slip10, or Bip32) which will specify how every master key that generated from a master seed would be a valid Ed25519 secret key (means will have the same keypair)

Simply, secret keys are only randomnes/entropies we can choose from.
Yorois 160 bits entropies are fine (for cherry-picking the right secret keys for master key), so why would not we chose only from them those only generates the same public key in both scheme the Ed25519 and Ed25519Bip32 (as it was originally in the Deadalus)?

The rationale of this, that every master key generated will be a valid `Ed25519` secret key (means both generate the same public key) that could be used in/with some other cryptographic libraries or in other tools that we're not aware of yet, but require `Ed25519` compatible key pairs.

In that case we can clearly separate the node level (that uses only `Ed25519` for verifying singatures) from the wallet level that use standardised (means only generate Ed25519 compatible key pairs) so importing a proper masterkey (which is a valid `Ed25519` secret key) will be always  `Ed25519-Bip32` on the wallet/jcli/client side.

So, if it would be applied, then `jcli` we should only have `Ed25519Extended` or `Ed25519Bip32` type of keys AND will only generate (based on some defined/standardised spec) ed `Ed25519` compatible secret keys similarly to the original `BIP32-ED25519` paper.
