### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by CodeSandwich** [input-output-hk/jormungandr#511]
Logger should be able to write to a plain text file. This is especially useful on Windows.

Possible difficulties:
- Slog tooling for file output may be poor
- Logger configuration must be extended with file path, which ideally should be enforced when output is file and forbidden for all other outputs

**Comment by gufmar** [comment]
Would it be possible to have an option who let jormungandr log to udp localhost instead of unix sockets? For example with https://docs.rs/syslog/4.0.1/syslog/
There is an existing free open-source syslog server also available for windows hosts. It can be configured to accept/filter/reformat and also redirect messages in many different ways. (For example redirect to a global testnet syslog server)
He can also parse new messages out from a logfile written by Jormungandr but the direct, fast and cool way would be to send the messages directly to the syslog service. 
Will help then also in a multiple proxy node setup.

**Comment by mzabaluev** [comment]
@gufmar Would GELF protocol support (pending in #497) solve your needs?

**Comment by onicrom** [comment]
+1 for syslog, adding config options for host, port, protocol, and facility

**Comment by mzabaluev** [comment]
Filed the syslog issue under #525. Please keep the discussion here to file-backed logging.

**Comment by gufmar** [comment]
> @gufmar Would GELF protocol support (pending in #497) solve your needs?

NXLog (the syslog server also available for Windows) supports GELF as an _output_ module but afaik not as an _input_ module (from Jromungandr)
So if GELF is used as the global testnet debug collector, NXLog can forward such messages after parsing plaintext (unstructured) messages from the local logfile.

**Comment by eugene-babichenko** [comment]
Regarding log file rotation, what kind of features do we want to have?

My suggestions are:

- Trigger rolling to the next file when the latest file:
  - reaches a particular size (for example, in megabytes)
  - have too many lines in it
  - becomes too old 
- Allow to set the maximal number of files to be stored and delete old files when required.
- Allow to set patterns for file names like `jormungandr.{}.log` where `{}` gets replaced by the log file number. The latest file has number 0.

**Comment by mzabaluev** [comment]
Gah no, don't bother with log rotation, it's the job for system services. Adding an option to redirect to a file should be quite enough.

**Comment by mzabaluev** [comment]
Good job @eugene-babichenko with #1118, I think we are done here.
