### ISSUE TITLE
Node crash if sending multiple transactions in the same slot

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#586]
**Describe the bug**
Node is crashing if we send multiple transactions in the same slot.

**To Reproduce**
1. generate files using: bash bootstrap -p 8607 -b | tee initialValues.txt
2. start the node with the suggested command: jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml
3. run the attached script (multipleTransactions.sh)

**Expected behavior**
Node should not crash.

**Additional context**
The script (multipleTransactions.sh) is creating an Account and then it sends funds thru 10 transactions from Faucet to the Account (using faucet-send-money.sh script).
If we add timeouts between transactions (= slot_duration), everything is ok.

Node and script logs (export RUST_BACKTRACE=1) attached.
[scriptLogs.txt](https://github.com/input-output-hk/jormungandr/files/3333582/scriptLogs.txt)
[nodeLogs.txt](https://github.com/input-output-hk/jormungandr/files/3333583/nodeLogs.txt)
[multipleTransactions.sh.txt](https://github.com/input-output-hk/jormungandr/files/3333595/multipleTransactions.sh.txt)

This bug was created in order to track https://github.com/input-output-hk/shelley-testnet/issues/22

**Comment by mzabaluev** [comment]
Thank you for the logs. @vincenthz have you narrowed it down to the specific unwrap?
It would help if you ran it on a debug build (`cargo run --bin jormungandr -- ...` in the source directory).

**Comment by rinor** [comment]
**os**: Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
**rustc --version**: rustc 1.35.0 (3c235d560 2019-05-20)
**node build from**: 71d73d4e1b1d64b9f2563ead6eb84c93168b475a

**command**: `RUST_BACKTRACE=full cargo run --bin jormungandr -- ...`

[bt-full2_testnet.log](https://github.com/input-output-hk/jormungandr/files/3335232/bt-full2_testnet.log)

**Comment by mzabaluev** [comment]
With #588 in, logging of the error should be more graceful now.

**Comment by rinor** [comment]
**node bulid from:** d239f842b15a322e5186372ba847e9268f15a41a

[bt-full3_testnet.log](https://github.com/input-output-hk/jormungandr/files/3344996/bt-full3_testnet.log)

**Comment by vincenthz** [comment]
so it seems that the process_block is returning the error due to the account signature invalidity.
it should really just be caught and thrown away as invalid block in the block process, but also not sure why we are queuing a bad block in the pipeline, definitely something worth looking into

**Comment by CodeSandwich** [comment]
After tracking down the bug is easy to solve:
1. Do not panic on invalid block (done, coming in PR)
2. When adding TXs from pool to block, apply them to the same ledger (done, coming in PR) (jormungandr/src/fragment/selection.rs:65 uses fresh copy for each TX making account counter not affected by previous TXs)

But the bigger picture is broken and not so simple to fix: it's virtually impossible to make multiple payments quickly using single account. REST API returns account TX counter from ledger. It's a constant value while slot is open. The wallet has to guess the order in which TXs will be processed and foresee the counters.

If I were writing a wallet, I would probably create a flood mechanism which in such cases would broadcast all possible orderings, which is good for my user, but bad for the network.
