### ISSUE TITLE
v0.2.3 Cannot Compile (Experimental Alpine Docker)

### ISSUE THREAD

**Issue by DavidArayan** [input-output-hk/jormungandr#590]
**Describe the bug**
Hey guys. First of all congratulations on getting the testnet out! very exciting stuff.

I'm running some experiments on my end, unofficial of course, to try and compile this repository on Docker using Alpine edge with Rust 1.35.0 (only available on edge). I've managed to iron out some of the issues myself, however i've hit a snag during the compile stage that fails, and I think it may be a missing library, I just cannot figure out which one. Any insight would be really helpful.

**To Reproduce**
Try to compile via Docker using alpine:edge, currently using the following libraries. Using version 0.2.3 of this repository, trying to compile from source.

RUN apk add --update --no-cache \
	git=2.22.0-r0 \
	curl=7.65.1-r0 \
	rust=1.35.0-r0 \
	cargo=1.35.0-r0 \
	openssl=1.1.1c-r0 \
	openssl-dev=1.1.1c-r0 

**Expected behavior**
To finish compiling the code

**Additional context**
Using an unofficial, experimental alpine docker image. Screenshot of error attached below.

<img width="1064" alt="Screen Shot 2019-06-28 at 12 25 07 pm" src="https://user-images.githubusercontent.com/7587896/60313773-b5c7cd00-99a3-11e9-830c-cf1f3b82af19.png">

**Comment by mzabaluev** [comment]
FYI, there's been a PR to maintain a Dockerfile for Alpine, using the -musl release builds that we build in our CI and post with releases: #567
Can you share a Dockerfile for the image you are trying to build?

`protoc` (the protobuf compiler) has to be found in `PATH`, or the absolute path of the binary has to be supplied in the environment variable `PROTOC`, for the network-grpc build to succeed.

The crate `prost` bundles a `protoc` binary as released by Google, which is a bad practice because the Linux binary depends on a dynamic glibc and this is not found in Alpine.  I have now filed an issue for prost to improve the diagnostics: danburkert/prost#202

**Comment by DavidArayan** [comment]
Thank you for reply, i've added the 'protoc' library (protobuf package for alpine) and will try again. Once compiled I plan to open source (MIT) and host the image in dockerhub to be used as a base for other functionality, I'll likely open the repo up later today or tomorrow. The versioning will be the same as this repository for consistency.

Now that i've got a clue, should be able to sort the issue out, cheers!

**Comment by DavidArayan** [comment]
Excellent, so for future reference if anyone has this issue, make sure to add the following packages in Dockerfile as `apk add protobuf protobuf-dev` and define `ENV PROTOC /usr/bin/protoc`. Package versions can be grabbed from `https://pkgs.alpinelinux.org/packages`. Performing these changes managed to compile the source in Alpine.

Thank you for your help @mzabaluev, will close this issue.

**Comment by DavidArayan** [comment]
Just for reference, i've opened up my repository at [Cardano Node](https://github.com/DavidArayan/cardano-node) that includes the WIP for the Alpine Docker Image. At the moment i've got it all compiling and running, i'm just fine tuning a few things to try and make the image as small as possible. I'll update the Readme there once its ready. Cheers!
