### ISSUE TITLE
Add fields useful for logs

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr#645]
**Is your feature request related to a problem/context ? Please describe if applicable.**
It's hard to determine if error logs coming into graylog are coming from up-to-date or previous versions to validate an issue has been fixed.

**Describe the solution you'd like**
Add a couple fields to the graylog output:
1. application: just "jormungandr"
2. version
3. epoch/block where applicable

**Comment by gufmar** [comment]
similar to #606

**Comment by mzabaluev** [comment]
> * application: just "jormungandr"

Can this be solved by using a distinctive graylog source (host) ID? We don't have any other applications sharing the same log drain.

> * version

I think this should better be logged once in an introductory message at the top of the log session of the process (also useful to distinguish different process runs in a continuous log), rather than repeated with every message, so this should belong in #606

> * epoch/block where applicable

The blockchain and leadership tasks could do this I think; the network task knows nothing about the blockchain state.
