### ISSUE TITLE
Extend `/node/stats` endpoint with "network stats"

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/jormungandr#769]
**Is your feature request related to a problem/context? Please describe if applicable.**
No technical way to find out how far the node is synced against the current target.

(I guess comparing `lastBlockTime` against `now()` might be used for it, but it seems like having actual given value might be more reliable and comparing height to height might be easier)

**Describe the solution you'd like**
It would be awesome, if possible, to add "last known network tip" info to the stats response, for example:
1. `lastRemoteBlockTime` - for the last known tip time
2. `lastRemoteBlockHeight` - for the last known tip height

**Additional context**
Having these values will allow to properly and easily handle situations when you need to programmatically monitor for whether the node is synced far enough for you to start other processes, for example. E.g. like if we need to block or redirect queries until the node is fully synced.

**Comment by vantuz-subhuman** [comment]
@CodeSandwich

**Comment by NicolasDP** [comment]
we are missing network information to be served to users in a useful way:

1. topology (know which blocks we consider our neighbourhood in the p2p topology);
2. network log activity (just like we do with the leaders and the fragment) be able to see what we are currently doing with the different peers (syncing (from? to?), gossiping, etc...);

**Comment by CodeSandwich** [comment]
Correct my understanding if I'm wrong.

The `lastRemoteBlock...` assumes that the node got information about existence of a new block from the network. This won't be useful if node has no connection with the network, because it'll keep returning the same data. It'll be useful only in the very slim time window between getting notification about new block and fetching its body, but even then in 99.9% of cases it'll be a 1 block difference.

To me the `lastBlockTime` seems most useful in context of deciding if state of the world is fresh enough to use.

One potentially useful information could be about predicted state of the network. E.g. how many blocks the current tip is behind what it should be based on wall clock. Or how many seconds.

**Comment by NicolasDP** [comment]
regarding `lastRemoteBlockTime`, And what is the time you display too? The time you receive it? Or you try to figure out the time it was created?

**Comment by NicolasDP** [comment]
All of these information are actually known in the node stats, example:

```
  "lastBlockTime": "2019-08-12T11:20:52.316544007+00:00",
  "lastBlockDate": "20.29",
  "lastBlockHeight": 202901,
  "lastBlockHash": "b9597b45a402451540e6aabb58f2ee4d65c67953b338e04c52c00aa0886bd1f0",
```

It shows the last block (the tip) details. The time denotes the time it appears for the first time to the node. When you are running a node that is not a stake pool, these info are the _Remote_ info.

**Comment by CodeSandwich** [comment]
@vantuz-subhuman I think that this issue is non-issue or resolved, so I'm going to close it. If you think otherwise, please let me know.
