### ISSUE TITLE
Leader node stops creating blocks

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#776]
**Describe the bug**
The node stops creating blocks after ~21 minutes. No actions are executed.

**Mandatory Information**
```
jcli --full-version
jcli 0.3.3 (master-17f43288, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```
```
jormungandr --full-version
jormungandr 0.3.3 (master-046b35b9, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. execute the bootstrap script using: `bash bootstrap -g -s 2 -e 30`
2. let the node running --> after ~21 minutes, no blocks are created anymore.

**Expected behavior**
The node should not stop to create blocks.

**Additional context**
OS: win10

[node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3600671/node_logs.txt)

[node_files.zip](https://github.com/input-output-hk/jormungandr/files/3600677/node_files.zip)

[blocks.zip](https://github.com/input-output-hk/jormungandr/files/3600679/blocks.zip)

**Comment by NicolasDP** [comment]
Thanks Dorin. This is fortunately not a bug. It’s mostly due to how Genesis Praos work. If you set a small amount of slot per epoch in the bootstrap script you will end up with very little blocks and maybe none at all. Set the epoch length to at least 100. Or change the Genesis Praos slot coefficient in the  Genesis config file (before creating the block 0) to have a more appropriate value.
