### ISSUE TITLE
Signature validation tool

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/jormungandr#893]
For the stake pool registry we need to be able to validate external signatures for files.

**Describe the solution you'd like**
At a minimum, something like the following command should terminate with exit status `0` or `1` ,
denoting success or failure of signature verification.

`jcli check-signature --pubkey BASE16 --content FILENAME --signature-type SIGFORMAT --signature FILENAME`

Additionally, in case of failure, the tool could print the reason on the standard error:

- whether it was an error in some of inputs (pubkey or signature), or
- whether it was a signature verification error.

**Comment by NicolasDP** [comment]
I believe by SIGFORMAT, you mean the signature scheme. We don't need it as we can get that from a bech32 encoded pubkey with with consistent prefix (i.e. same as any generated keys in `jcli`).

so it will be:

add `jcli key sign`:

* `--secret-key <PATH_TO_SECRET_FILE>: bech32 encoded secret key as outputed by `jcli key generate`.
* `--data <PATH_TO_DATA_FILE>`: unless present, will be read from the standard input. Bytes... no specific format expected.
* `--output <PATH_TO_WRITE_OUTPUT_TO>: unless present will be printed to the standard output. In bech32.

and add `jcli key verify`:

* `--public-key <PATH_TO_PUBLIC_KEY>`: bech32 encoded public key as outputed by `jcli key to-public`.
* `--data <PATH_TO_DATA_FILE>`: unless present, will be read from the standard input. Bytes... no specific format expected.
* `--signature <SIGNATURE_FILE>`: as printed by `jcli key sign`.

This function will return `0` on success, something else otherwise and optionally an error message on the standard error.

**Comment by deepfire** [comment]
@NicolasDP, I'd prefer us to have an additional option of supplying the pubkey as a base16 string -- not even a file.

**Comment by deepfire** [comment]
Integrated in https://github.com/input-output-hk/testnet-stake-pool-registry-validator .
